In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import numpy as np
import requests
import pickle
import io

# Import the preprocessed data
X_preprocessed_url = "https://static.bc-edx.com/ai/ail-v-1-0/m19/lesson_2/datasets/pickles/preprocessed_fungi.pkl"
y_url = "https://static.bc-edx.com/ai/ail-v-1-0/m19/lesson_2/datasets/pickles/fungi_y.pkl"

X = pickle.load(io.BytesIO(requests.get(X_preprocessed_url).content))
y = pickle.load(io.BytesIO(requests.get(y_url).content))

print(X[0])
print(y.head())


[[[0.5568628  0.5647059  0.56078434]
  [0.5568628  0.5647059  0.56078434]
  [0.5568628  0.5647059  0.56078434]
  ...
  [0.53333336 0.54901963 0.54509807]
  [0.5372549  0.5529412  0.54901963]
  [0.5372549  0.5529412  0.54901963]]

 [[0.54901963 0.5568628  0.5529412 ]
  [0.54901963 0.5568628  0.5529412 ]
  [0.5529412  0.56078434 0.5568628 ]
  ...
  [0.53333336 0.54901963 0.54509807]
  [0.5372549  0.5529412  0.54901963]
  [0.5372549  0.5529412  0.54901963]]

 [[0.53333336 0.5411765  0.5372549 ]
  [0.5411765  0.54901963 0.54509807]
  [0.54901963 0.5568628  0.5529412 ]
  ...
  [0.5254902  0.5411765  0.5372549 ]
  [0.5294118  0.54509807 0.5411765 ]
  [0.5294118  0.54509807 0.5411765 ]]

 ...

 [[0.5529412  0.53333336 0.4509804 ]
  [0.5529412  0.53333336 0.4509804 ]
  [0.54901963 0.5254902  0.44705883]
  ...
  [0.54509807 0.5529412  0.5568628 ]
  [0.54509807 0.5529412  0.56078434]
  [0.54509807 0.5529412  0.56078434]]

 [[0.54901963 0.5254902  0.44705883]
  [0.54901963 0.5254902  0.44705883]


In [2]:
# Label encode the y data
y_encoder = LabelEncoder().fit(y)
y = y_encoder.transform(y)

# Convert values to numpy arrays
X = np.array(X)

# Split the training dataset into training and validation sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Define a CNN model; I need to make sure to use the correct values for input shape
model = keras.Sequential([
    layers.Conv2D(32, (3, 3), activation='relu', input_shape=(250, 250, 3)),
    layers.MaxPooling2D((2, 2)),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(2, activation='sigmoid')
])

# Compile the model
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

# Train the model
batch_size = 32
epochs = 10
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=epochs
)

Epoch 1/10


/Users/stevenhill/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/layers/convolutional/base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


7/7 ━━━━━━━━━━━━━━━━━━━━ 2s 166ms/step - accuracy: 0.4476 - loss: 10.7647 - val_accuracy: 0.7000 - val_loss: 2.9044
Epoch 2/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 153ms/step - accuracy: 0.5155 - loss: 1.9527 - val_accuracy: 0.7000 - val_loss: 0.8647
Epoch 3/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 150ms/step - accuracy: 0.5666 - loss: 0.9126 - val_accuracy: 0.7200 - val_loss: 0.6016
Epoch 4/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 148ms/step - accuracy: 0.6301 - loss: 0.7295 - val_accuracy: 0.7600 - val_loss: 0.6121
Epoch 5/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 148ms/step - accuracy: 0.6584 - loss: 0.6473 - val_accuracy: 0.7200 - val_loss: 0.5662
Epoch 6/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - accuracy: 0.6878 - loss: 0.6322 - val_accuracy: 0.7200 - val_loss: 0.5826
Epoch 7/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 151ms/step - accuracy: 0.6512 - loss: 0.6255 - val_accuracy: 0.7200 - val_loss: 0.5638
Epoch 8/10
7/7 ━━━━━━━━━━━━━━━━━━━━ 1s 149ms/step - accuracy: 0.6527 - loss: 0.6194 - val_accuracy: 0.7400 - val_loss: 0.5572
Ep